version: '3.5'

networks:
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 142.2.0.0/16
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 142.1.0.0/16

services:
#database
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: seg123
    networks:
      - back

#Worpress
  app:
    depends_on:
      - db
      - cache
    build:
      context: ./conf/wp
      dockerfile: Dockerfile
    restart: always
    environment:
      VIRTUAL_HOST: chenchenia.padoru
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_PASSWORD: seg123
      WORDPRESS_TABLE_PREFIX: wpt_
    #expose:
    #  - "80"
    #  - "443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - front
      - back

#Load_Balancer
  proxy:
    build:
      context:  ./conf/proxy
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - front


#redis
  cache:
    image: redis
    depends_on:
      - db
    #volumes:
    #  - ./conf/cache/redis.conf::/usr/local/etc/redis/redis.conf
    networks:
      - back

    #command: redis-server /usr/local/etc/redis/redis.conf


#IP

volumes:
  db_data:
  wordpress_files:
