version: '3.5'

services:
#database
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: seg123

#Worpress
  app:
    depends_on:
      - db
      - cache
    build:
      context: ./conf/wp
      dockerfile: Dockerfile
    restart: always
    environment:
      VIRTUAL_HOST: chenchenia.padoru
      WP_CACHE: true
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: db
      WORDPRESS_DB_PASSWORD: seg123
      WORDPRESS_TABLE_PREFIX: wpt_
    #expose:
    #  - "80"
    #  - "443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - front
      - back

#Load_Balancer
  proxy:
    build:
      context:  ./conf/proxy
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      front:
        ipv4_address: 142.1.0.20

#redis
  cache:
    image: redis
    volumes:
      - ./conf/cache/redis.conf::/usr/local/etc/redis/redis.conf
    networks:
      back:
        ipv4_address: 142.2.0.7
    command: redis-server /etc/redis/redis.conf


#IP
networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 142.2.0.0/16
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 142.1.0.0/16

volumes:
  db_data:
  wordpress_files:
